# Generated by Django 3.2.10 on 2022-03-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_recipes',
            field=models.ManyToManyField(related_name='liked_by', to='app.Recipe'),
        ),
    ]
